---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    component: alertmanager
  name: prometheus-alertmanager
data:
  alertmanager.yml: |-
    global:
      # ref:  https://typesafe.slack.com/apps/new/incoming-webhooks

    receivers:
      - name: default
      #  slack_configs:
      #  - channel: '#es-alert'
      #    send_resolved: true

    route:
      receiver: default
      group_by: [es_workload]

    # don't alert on warnings if the same alert is already critical
    inhibit_rules:
    - source_match:
        severity: critical
      target_match:
        severity: warning
      equal: [alertname]

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: prometheus
    component: alertmanager
  name: prometheus-alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: alertmanager
  template:
    metadata:
      labels:
        app: prometheus
        component: alertmanager
    spec:
      serviceAccountName: default
      containers:
        - name: prometheus-alertmanager
          image: prom/alertmanager:{{ .Values.alertManagerVersion }}
          env:
          args:
            - --config.file=/etc/config/alertmanager.yml
            - --storage.path=/data

          ports:
            - containerPort: 9093
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9093
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9093
            timeoutSeconds: 30
            initialDelaySeconds: 30

          volumeMounts:
            - name: config-volume
              mountPath: /etc/config

        - name: prometheus-alertmanager-configmap-reload
          image: jimmidyson/configmap-reload:{{ .Values.configMapReloadVersion }}
          args:
            - --volume-dir=/etc/config
            - --webhook-url=http://localhost:9093/-/reload
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-alertmanager

{{ if .Values.minikube }}
---
apiVersion: v1
kind: Service
metadata:
  name: expose-alertmanager
spec:
  ports:
  - port: 9093
    protocol: TCP
    targetPort: 9093
    nodePort: 30093
  selector:
    app: prometheus
    component: alertmanager
  type: NodePort
{{ end }}
