{{ if (and .Values.createAlertManager .Values.usePersistentVolumes) }}
kind: PersistentVolumeClaim
apiVersion: {{ .Values.coreApiVersion }}
metadata:
  name: alertmanager-storage
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: alertmanager
spec:
  {{ if or .Values.defaultStorageClass .Values.esAlertmanagerStorageClass }}
  storageClassName: {{ default .Values.defaultStorageClass .Values.esAlertmanagerStorageClass }}
  {{ end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.alertmanagerVolumeSize }}
{{ end }}
