apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: console-frontend
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: console-frontend

spec:
  selector:
    matchLabels:
      run: es-console

  template:
    metadata:
      annotations:
        checksum/es-console-config: {{ include (print $.Template.BasePath "/es-console-configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ template "name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: console-frontend
        # Deprecated - these should be removed eventually. Kept to support upgrades with the old labels.
        run: es-console
    spec:
      {{ if .Values.podUID }}
      securityContext:
        runAsUser: {{ .Values.podUID }}
      {{ end }}

      imagePullSecrets:
      - name: commercial-credentials

      containers:
      # Used by nginx to look up service names dynamically.
      # go-dnsmasq has the unique property of using /etc/resolv.conf search domains.
      - name: dnsmasq
        image: {{ .Values.goDnsmasqImage }}:{{ .Values.goDnsmasqVersion }}
        args:
          - --listen
          - "127.0.0.1:5353"
          - --verbose
          - --enable-search

      - name: es-console
        image: {{ tpl .Values.esConsoleImage . }}:{{ .Values.esConsoleVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          requests:
            cpu: {{ default .Values.defaultCPURequest .Values.esConsoleCPURequest }}
            memory: {{ default .Values.defaultMemoryRequest .Values.esConsoleMemoryRequest }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: ui-config
          mountPath: /helm-data/assets/js

      volumes:
      - name: nginx-config
        configMap:
          name: console-frontend
          items:
          - key: default.conf
            path: default.conf
      - name: ui-config
        configMap:
          name: console-frontend
          items:
          - key: config.js
            path: config.js
