apiVersion: v1
kind: ConfigMap
metadata:
  name: console-frontend
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    com.lightbend.cloudflow/instance-id: {{ .Release.Name }}
    app.kubernetes.io/component: console-frontend
data:
{{ (tpl (.Files.Glob "console-frontend/*").AsConfig .) | indent 2 }}
