apiVersion: {{ .Values.coreApiVersion }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grafana-datasource-cm
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
data:
  prometheus-server-datasource.yaml: |
    # config file version
    apiVersion: 1

    # list of datasources to insert/update depending
    datasources:
      # <string, required> name of the datasource. Required
    - name: Cinnamon Prometheus
      # <string, required> datasource type. Required
      type: prometheus
      # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
      access: proxy
      # <int> org id. will default to orgId 1 if not specified
      orgId: 1
      # <string> url
      url: http://prometheus-server
      #
      basicAuth: false
      #
      isDefault: true
      editable: true
