apiVersion: {{ .Values.coreApiVersion }}
kind: ConfigMap
metadata:
  name: exporter-graphs-cm
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
data:
{{ (.Files.Glob "es-grafana/*").AsConfig | indent 2 }}
