---
apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: REPLACE_IMAGE
  newName: registry.lightbend.com/lightbend-console-operator
  newTag: latest
kind: Kustomization
namespace: lightbend
resources:
- console_crd.yaml
- operator.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
