apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy/service_account.yaml
  - deploy/role.yaml
  - deploy/role_binding.yaml
  - deploy/cluster_role.yaml
  - deploy/cluster_role_binding.yaml
  - deploy/operator.yaml